#!/usr/bin/env bash
# ############################################################################
# A special script for GitHub Action pipeline to show a result after the docker image was build.
#
# Usage:
# ./github-docker-build-status "${IMAGE_NAME}" "${IMAGE_VERSION}" "${REPO_IMAGE_VERSION}" "${{ steps.docker_build.outputs.digest }}"
#
# ############################################################################
IMAGE_NAME="${1:-"${IMAGE_NAME:-"0.0.1"}"}"
IMAGE_VERSION="${2:-"${IMAGE_VERSION:-"0.0.1"}"}"
REPO_IMAGE_VERSION="${3:-"${REPO_IMAGE_VERSION:-"0.0.1"}"}"
IMAGE_HASH="${4:-""}"
GITHUB_STEP_SUMMARY="${GITHUB_STEP_SUMMARY:-"/dev/stdout"}"

if [ "${IMAGE_VERSION}" != "${REPO_IMAGE_VERSION}" ]; then
  if [ -n "${IMAGE_HASH}" ]; then
    echo " * ${IMAGE_NAME}:${IMAGE_VERSION} - ${IMAGE_HASH}"
  else
    echo " * ${IMAGE_NAME}:${IMAGE_VERSION}"
  fi
  echo "### :ok_hand: :white_check_mark: Docker image ${IMAGE_NAME}:${IMAGE_VERSION} was created!" >> $GITHUB_STEP_SUMMARY
else
  echo "### :white_check_mark: Skip create docker image '${IMAGE_NAME}'. Version ${IMAGE_VERSION} already exists." >> $GITHUB_STEP_SUMMARY
fi