#!/usr/bin/env bash
set -e
# ############################################################################
# A script for Github Action step to work in the docker image source repository
# 
# ############################################################################
GITHUB_URL="https://raw.githubusercontent.com/revgen"
GITHUB_ENV=${GITHUB_ENV:-"/dev/stdout"}
NEED_DELETE_DOCKER_IMAGE_SCRIPT=0
error() {
    if [ ${NEED_DELETE_DOCKER_IMAGE_SCRIPT} -ne 0 ]; then rm -f ./docker-image; fi
    exit "${1:-0}"
}
if [ ! -f ./docker-image ]; then
    NEED_DELETE_DOCKER_IMAGE_SCRIPT=1
    echo "Script docker-image not found, downloading..."
    curl -sL "${GITHUB_URL}/revgen/refs/heads/master/.github/scripts/docker-image" > docker-image || error 1
    echo "Script docker-image was downloaded."
fi

IMAGE_NAME=${1:-"${IMAGE_NAME}"}
echo "Get docker image version..."
image_name="$(bash ./docker-image name)"
if [ -z "${image_name}" ]; then
    echo "Error: image name not found"; error 1;
fi
image_version="$(bash ./docker-image version)"
if [ -z "${image_version}" ]; then
    echo "Error: image version not found"; error 1;
fi
echo "Found version: ${image_name} v${image_version}"

echo "Check existing version"
repo_image_version="$(bash ./docker-image latest-version)"

IMAGE_NAME="${image_name:-"unknown"}"
IMAGE_VERSION="${image_version:-"0.0.1"}"
REPO_IMAGE_VERSION="${repo_image_version:-"null"}"

echo "Image remote version is ${REPO_IMAGE_VERSION}"
if [ -n "${GITHUB_ENV}" ]; then
    # We need to store system enviornment for Github Action steps
    echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
    echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
    echo "REPO_IMAGE_VERSION=$REPO_IMAGE_VERSION" >> $GITHUB_ENV
else
    echo "IMAGE_NAME=$IMAGE_NAME"
    echo "IMAGE_VERSION=$IMAGE_VERSION"
    echo "REPO_IMAGE_VERSION=$REPO_IMAGE_VERSION"
fi

if [ "${IMAGE_VERSION}" == "${REPO_IMAGE_VERSION}" ]; then
    echo "Version ${IMAGE_NAME}:${IMAGE_VERSION} already exists on the registry."
    error 1
fi

echo "Image ${IMAGE_NAME}:${IMAGE_VERSION} need to be pushing to the registry."
error 0
